# Generated by Django 2.0.5 on 2018-05-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Specified')], default='NS', max_length=2),
        ),
    ]
