# Generated by Django 2.0.5 on 2018-05-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
